baseurl = "https://berto.github.io"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Roberto Ortega"
title = "Berto"
disqusshortname = "BertoBlog"
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Example blog"
logofile = "img/zergling.svg"
faviconfile = "img/zergling.png"
highlightjs = true
lang = "en"
github = "berto"
email = "berto.ort@gmail.com"
linkedin = "bertoort"

[markup.goldmark]
  [markup.goldmark.renderer]
    hardWraps = false
    unsafe = true
    xhtml = false